#
# PHP-FPM + Nginx + MariaDB Docker-Compose
#
# Written by:
#   Baptiste MOINE <contact@bmoine.fr>
#

version: '3.0'
networks:
    back:
        driver: bridge
    front:
        driver: bridge
services:
    db:
        image: mariadb:latest
        container_name: db
        environment:
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: app-admin
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin-app
        ports:
            - 3306:3306/tcp
        networks:
            - back
        restart: always
        volumes:
            - ${ROOT}/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - dbdata:/var/lib/mysql:rw
    gitlab:
        image: gitlab/gitlab-ce:8.17.0-ce.0
        container_name: gitlab
        environment:
            GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.dev/'; gitlab_rails['lfs_enabled'] = true;"
        ports:
            - 2222:22/tcp
        networks:
            - front
        restart: always
        volumes:
            - gitlab:/var/opt/gitlab:rw
    stackedit:
        build: build/stackedit
        container_name: stackedit
        environment:
            HOST: 0.0.0.0
            PORT: 80
        networks:
            - front
        restart: always
        volumes:
            - ${ROOT}/conf/stackedit/server.js:/stackedit/server.js:ro
    http:
        build: build/nginx
        container_name: http
        links:
            - gitlab
            - php
            - stackedit
        ports:
            - 80:80/tcp
            - 443:443/tcp
        networks:
            - front
        restart: always
        volumes:
            - ${ROOT}/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ${ROOT}/conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ${ROOT}/data/www/webroot:/usr/share/nginx/webroot:ro
            - ${ROOT}/data/www/lab:/usr/share/nginx/lab:ro
            - ${ROOT}/data/www/vendor:/usr/share/nginx/vendor:ro
            - ${ROOT}/data/www/static:/usr/share/nginx/static:ro
            - ${ROOT}/log/nginx:/usr/share/nginx/log:rw
    php:
        build: build/php-fpm
        container_name: php
        links:
            - db
        privileged: true
        networks:
            - back
            - front
        restart: always
        command: php-fpm --allow-to-run-as-root
        volumes:
            - ${ROOT}/conf/php-fpm/www.conf:/etc/php5/fpm/pool.d/www.conf:ro
            - ${ROOT}/conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${ROOT}/data/www/webroot:/usr/share/nginx/webroot:ro
            - ${ROOT}/data/www/lab:/usr/share/nginx/lab:ro
            - ${ROOT}/data/www/vendor:/usr/share/nginx/vendor:rw
volumes:
    dbdata:
        driver: local
    gitlab:
        driver: local

