#
# PHP-FPM + Nginx + MariaDB Docker-Compose
#
# Written by:
#   Baptiste MOINE <bap.moine.86@gmail.com>
#

version: '2.0'
networks: {}
services:
    db:
        image: mariadb:latest
        container_name: db
        environment:
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: app-admin
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin-app
        ports:
            - 3306:3306/tcp
        restart: always
        volumes:
            - //var/host/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - dbdata:/var/lib/mysql:rw
    gitlab:
        image: gitlab/gitlab-ce:8.9.6-ce.0
        container_name: gitlab
        environment:
            GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.dev/'; gitlab_rails['lfs_enabled'] = true;"
        ports:
            - 2222:22/tcp
        restart: always
        volumes:
            - gitlab:/var/opt/gitlab:rw
    http:
    stackedit:
        build: build/stackedit
        container_name: stackedit
        environment:
            HOST: 0.0.0.0
            PORT: 80
        restart: always
        volumes:
            - //var/host/conf/stackedit/server.js:/stackedit/server.js:ro
        build: build/nginx
        container_name: http
        links:
            - gitlab
            - php
            - stackedit
        ports:
            - 80:80/tcp
            - 443:443/tcp
        restart: always
        volumes:
            - //var/host/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - //var/host/conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - //var/host/data/www/webroot:/usr/share/nginx/webroot:ro
            - //var/host/data/www/lab:/usr/share/nginx/lab:ro
            - //var/host/data/www/vendor:/usr/share/nginx/vendor:ro
            - //var/host/data/www/static:/usr/share/nginx/static:ro
            - //var/host/log/nginx:/usr/share/nginx/log:rw
    php:
        build: build/php-fpm
        container_name: php
        links:
            - db
        privileged: true
        restart: always
        command: php-fpm --allow-to-run-as-root
        volumes:
            - //var/host/conf/php-fpm/www.conf:/etc/php5/fpm/pool.d/www.conf:ro
            - //var/host/conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - //var/host/data/www/webroot:/usr/share/nginx/webroot:ro
            - //var/host/data/www/lab:/usr/share/nginx/lab:ro
            - //var/host/data/www/vendor:/usr/share/nginx/vendor:rw
volumes:
    dbdata:
        driver: local
    gitlab:
        driver: local

